#!/bin/bash
#
#xdg-open "https://www.google.com/search?tbm=isch&q=Autosan+M09LE+Sancity+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+8,9LE+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Volvo+7900+Hybrid+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+18+hybrid+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Volvo+7900A+Hybrid+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Mercedes-Benz+O530+Citaro+C2+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+18+IV+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+12+IV+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+12+mild+hybrid+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+12+III+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Mercedes+Conecto+G+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Mercedes-Benz+O530G+Citaro+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+12+III+electric+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+8,9LE+electric+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+12+IV+electric+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Irizar+ie+bus+12+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+12,9+hybrid+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+18+IV+electric+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+18+III+electric+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Mercedes+Conecto+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Mercedes-Benz+O530+Citaro+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+18+III+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=MAN+Lion's+Intercity+LE+13+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Karsan+Jest+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Mercedes-Benz+Sprinter+City+75+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Automet+Cityliner+Smile+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Solaris+Urbino+18+MetroStyle+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Autosan+M12LF+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=MMI+Iveco+Urby+LE+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=MMI+Iveco+Urby+LE+electric+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=MAN+Lion's+City+18+CNG+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Scania+Castrosua+New+City+CNG+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=Scania+Castrosua+New+City+10+CNG+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=AMZ+City+Smile+CS12LF+Kraków" >/dev/null 2>&1 &
#xdg-open "https://www.google.com/search?tbm=isch&q=AMZ+City+Smile+CS10LF+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=PESA+2014N+„Twist”+(Krakowiak)+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Konstal/Protram+405N-Kr+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Düwag+N8C-NF+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=MAN+N8S-NF+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Bombardier-Rotax/MPK+EU8N+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=SGP/Lohner+E1+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=SGP/Lohner+E1+c3+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Stadler+Tango+„Lajkonik+II”+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Stadler+Tango+„Lajkonik”+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Düwag+GT8N+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Düwag+GT8C+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Düwag+GT8SU+Kraków" >/dev/null 2>&1 &
xdg-open "https://www.google.com/search?tbm=isch&q=Bombardier+NGT6+Kraków" >/dev/null 2>&1 &
